name: eodms-api-client-rtd
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - alabaster=0.7.12=py37_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - babel=2.9.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.12.8=h06a4308_0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.12.5=py37h06a4308_0
  - cffi=1.14.0=py37h2e261b9_0
  - cfitsio=3.470=hb7c8383_2
  - chardet=3.0.4=py37h06a4308_1003
  - click=7.1.2=py_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.1=py37h06a4308_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cryptography=3.3.1=py37h3c74f83_0
  - curl=7.67.0=hbc83047_0
  - docutils=0.16=py37_1
  - expat=2.2.10=he6710b0_2
  - fiona=1.8.13.post1=py37hc820daa_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.4=h5ab3b9f_0
  - freexl=1.0.6=h27cfd23_0
  - gdal=3.0.2=py37hbb2a789_0
  - geopandas=0.8.1=py_0
  - geos=3.8.0=he6710b0_0
  - geotiff=1.5.1=h21e8280_1
  - giflib=5.1.4=h14c3975_1
  - glib=2.63.1=h5a9c865_0
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=2.10=py_0
  - imagesize=1.2.0=py_0
  - intel-openmp=2020.2=254
  - jinja2=2.11.2=py_0
  - jpeg=9b=h024ee3a_2
  - json-c=0.13.1=h1bed415_0
  - kealib=1.4.7=hd0c454d_6
  - krb5=1.16.4=h173b8e3_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libboost=1.67.0=h46d08c1_4
  - libcurl=7.67.0=h20c2e04_0
  - libdap4=3.19.1=h6ec2957_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgdal=3.0.2=h27ab9cc_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libkml=1.3.0=h590aaf7_4
  - libnetcdf=4.6.1=h11d0813_2
  - libpng=1.6.37=hbc83047_0
  - libpq=11.2=h20c2e04_0
  - libspatialindex=1.9.3=he6710b0_0
  - libspatialite=4.3.0a=h793db0d_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.8.1.2=h14c3975_0
  - markupsafe=1.1.1=py37h14c3975_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - munch=2.5.0=py_0
  - ncurses=6.2=he6710b0_1
  - numpy=1.19.2=py37h54aff64_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1i=h27cfd23_0
  - packaging=20.8=pyhd3eb1b0_0
  - pandas=1.1.5=py37ha9443f7_0
  - pcre=8.44=he6710b0_0
  - pip=20.3.3=py37h06a4308_0
  - pixman=0.40.0=h7b6447c_0
  - poppler=0.65.0=h581218d_1
  - poppler-data=0.4.10=h06a4308_0
  - postgresql=11.2=h20c2e04_0
  - proj=6.2.1=haa6030c_0
  - pycparser=2.20=py_2
  - pygments=2.7.3=pyhd3eb1b0_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=py_0
  - pyproj=2.6.1.post1=py37hd003209_1
  - pysocks=1.7.1=py37_1
  - python=3.7.7=h191fe78_0_cpython
  - python-dateutil=2.8.1=py_0
  - pytz=2020.4=pyhd3eb1b0_0
  - readline=7.0=h7b6447c_5
  - requests=2.24.0=py_0
  - rtree=0.9.4=py37_1
  - setuptools=51.0.0=py37h06a4308_2
  - shapely=1.7.1=py37h98ec03d_0
  - six=1.15.0=py37h06a4308_0
  - snowballstemmer=2.0.0=py_0
  - sphinx=3.4.0=pyhd3eb1b0_0
  - sphinx_rtd_theme=0.4.3=py_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sqlite=3.33.0=h62c20be_0
  - tbb=2018.0.5=h6bb024c_0
  - tiledb=1.6.3=h1fb8f14_0
  - tk=8.6.10=hbc83047_0
  - tqdm=4.51.0=pyhd3eb1b0_0
  - urllib3=1.25.11=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xerces-c=3.2.3=h780794e_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - eodms-api-client==0.1.1
